### ISSUE TITLE
Model references could not be exported into .slx

### ISSUE THREAD

**Issue by phanthanhliem** [viatra/massif#20]
Hi,

I'am trying to test the import and export of model references, but it seems there is a problem.

I have three simple simulink models :  
a constant model (constant.slx), 
![image](https://cloud.githubusercontent.com/assets/10292378/5700837/0c5527c6-9a44-11e4-9e12-fb0f0e809dd0.png)

a multiply model (multiply.slx) and 
![image](https://cloud.githubusercontent.com/assets/10292378/5700849/2900f40e-9a44-11e4-9902-617d37e4ce1e.png)

a gain model (gain.slx). 
![image](https://cloud.githubusercontent.com/assets/10292378/5700843/1bb8d5dc-9a44-11e4-91c4-cdeed99a24d8.png)

Then I create a composite model (composite) to compose the above models (in the form model references) together. These models have been verified in simulink.
![image](https://cloud.githubusercontent.com/assets/10292378/5700769/127489d6-9a43-11e4-9724-eba1cdf22a5b.png)

By selecting the shallow, deep or referencing mode, i could transform composite_SPIDER.slx into composite.simulink.  How ever, when i did the inverse to tranform composite.simulink into .slx,
there is always an error:
![image](https://cloud.githubusercontent.com/assets/10292378/5700804/84e1220e-9a43-11e4-987b-6c831b36a605.png)

![image](https://cloud.githubusercontent.com/assets/10292378/5700801/77b4fb46-9a43-11e4-962b-5367ce4777f3.png)

Do you have any clue about this kind of error?
Thank you for your help.

Best regards.
Thanh Liem PHAN.

**Comment by abelhegedus** [comment]
Just a quick check:
1. Do you simply import the model with the chosen mode and then re-export it again *without* changing anything?
2. Are the models open in your Matlab during the export?
3. Do you change anything in Matlab between the import and the export? (restarting, opening models, changing path, etc.)
4. Is any file created during the export?

We are trying to reproduce the problem and find a fix or workaround.

**Comment by phanthanhliem** [comment]
Hi abelhegedus,

Here are my answers:
1. Do you simply import the model with the chosen mode and then re-export it again without changing anything?
Yes.

2. Are the models open in your Matlab during the export?
No.

3. Do you change anything in Matlab between the import and the export? (restarting, opening models, changing path, etc.)
No, i didn't change anything, just import and then re-export immediately.

4. Is any file created during the export?
No, no file has been created.

I could send you the simulinks models, if it is necessary.
Regards.
PTL.

**Comment by imbur** [comment]
Hi phanthanhliem,

Here are some more things to check:
 * After the occurrence of the error during export, in the running Matlab session try to open the composite_SPIDER by calling the `open_system('composite_SPIDER')` command. Is it succesful? You should get an empty model.
 * If the above command fails, try to create the system yourself: `new_system('composite_SPIDER')`
 * At this point calling `add_block('simulink/Ports & Subsystems/Model','composite_SPIDER/constant_2')` should be successful.

Could you also collect the output values of the `new_system` and `add_block` commands? (Assign them to a variable like `output = new_system('mysystem')` and see the output on the console)

**Comment by phanthanhliem** [comment]
Hi,

The problem is partially solved. I described the context to well understand the problem:

A. Error export scenario
1. Import simulink file : 
Input : composite_SPIDER.slx
Output : composite_shallow.simulink. Here, in fact, i've tried to modified the default output Model Name from composite_SPIDER into composite_shallow. And may be this is the source of error.

2. Export
Input: composite_shallow.simulink
Output : error as you see.

B. Correct export scenario
1. Import simulink file : 
Input : composite_SPIDER.slx
Output : composite_SPIDER.simulink. (the default Model Name)
2. Export
Input: composite_SPIDER.simulink
Output : composite_SPIDER.mdl. OK

I've verified the destination model, it seems that all infor are transformed correctly.
However, when i tried to lunch the simulation, there is an error like this
![image](https://cloud.githubusercontent.com/assets/10292378/5703195/b2447730-9a63-11e4-8246-c94316e14226.png)

It says that there is a mismatch between the Dataset format for signal logging between the top model (composite_SPIDER) and the referenced models (constant_SPIDER, multiply_SPIDER,...).

The origine simulink model is .slx, and the destination re-export model is in format .mdl.
Is this the source of the error above? Could we select the export format (mdl or slx)?
And why, in this case, is .mdl but not .slx?

Regards.
PTL.

**Comment by phanthanhliem** [comment]
Hi,

I've got it : the property "signal logging format" is not preserved in the import-export process, 
In fact, there is no info of "signal logging format" in the intermediate model .simulink.
So I think the problem is because of the loading of default parameters of .slx is not the same as .mdl?

In this case, just open Model Configuration Parameters, and change it from Dataset to ModelDataLogs, and the simulation works perfectly.
![image](https://cloud.githubusercontent.com/assets/10292378/5703330/9b8a28da-9a65-11e4-8fad-c0a9e1f15899.png)

I will test with a more complicated example.
Thanks & Brdgs.
PTL

**Comment by abelhegedus** [comment]
Great to hear that you could work around the issue.

If I understand right, there is a model configuration parameter that you haven't set manually in your input model, thus the defaults were used. Then since the exporter did not set these properties, the defaults are used again, but for some reason, this default is different in case of MDL format.

@imbur can you check the following hypothesis:
- create an empty MDL and a different empty SLX. Check the model configuration on both. These values should be the same. Are they?

Also, we will need to add the option to select MDL or SLX output format in the exporter. Currently, only MDL is provided, although I guess SLX can be supported simply by setting a different file extension in the `save_system` command

**Comment by phanthanhliem** [comment]
Yes, it is exactly as you think.
A choice to save in .MDL or .SLX is great.

**Comment by imbur** [comment]
Hi,

I checked Ábel's assumption, but the only difference that the model comparator showed me between an empty mdl and an empty slx model is that one of the parameters contained 0.0 in the former, and 0U in the latter case (DataLoggingOverride). I guess this tiny difference should cause no problems, so that some investigation is still needed on the topic.

With commit ee386e351df9820ffdbe20ab51668dd515f76881 the users have the option to save models in the desired (mdl or slx) format. I have updated the example code as well, however the changes are not yen on the Wiki, but they are trivial to use.

Best regards,
Marton
