### ISSUE TITLE
Get it running 

### ISSUE THREAD

**Issue by claudiazanabria** [viatra/massif#70]
Dear all,

My configuration is: 
Viatra 1.5.0 , I got from http://download.eclipse.org/viatra/updates/release/1.5.0/ 
Matlab 2016a
Massif 0.6.0.201606031721, I got from http://static.incquerylabs.com/projects/massif/integration/ 
massif.commandevaluation.server-integration_0.6.0.201606031721
Ecipse Neon
Java verion: 1.8.0_151

when I tried to use the connector Comman Evaluation Server in Matlab I get this error at running setup_remote.m:

**Undefined variable "br" or class "br.com.embraer.massif.commandevaluation.server.ServerEntryPoint".

Error in setup_remote (line 17)
modelProviderServer = br.com.embraer.massif.commandevaluation.server.ServerEntryPoint;**

when I try to use Matlab control, I get this error in Eclipse:

![image](https://user-images.githubusercontent.com/16934962/33848620-9a7fcfea-deae-11e7-94fb-7a95e8b87028.png)

Could you please help me to resolve this issue.

Many thanks

Best regards,

Claudia Zanabria

**Comment by abelhegedus** [comment]
Hi!

I assume that you are trying to export a Simulink model from Eclipse to MATLAB using the Eclipse UI integration of Massif as described on the [wiki](https://github.com/viatra/massif/wiki/UserGuide#model-export).

For Matlab control, you get this exception if the MatlabProxy is null, which happens if MC cannot connect to MATLAB, maybe because it got the wrong options. Does MATLAB start when you invoke the export?

For CE Server, this error occurs if there are problems with loading the classes by MATLAB. You have to make sure, that you set the current directory to the one containing the jars before you execute the setup_remote.m (see [wiki](https://github.com/viatra/massif/wiki/UserGuide#command-evaluation-server-matlabserver) ).

**Comment by abelhegedus** [comment]
Closing for now, please reopen with specifics if still relevant. Thanks!
